/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Controller;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import model.Mahasiswa;

/**
 *
 * @author user
 */
public class MahasiswaView extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    private String mahasiswaId;
    private Controller controller;
    
    /**
     * Creates new form BendaharaView
     * @param contentScrollPane
     */
    public MahasiswaView(JScrollPane contentScrollPane, String mahasiswaId) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
        this.mahasiswaId = mahasiswaId;
        this.controller = new Controller();
        initComponents();
        loadMahasiswaData();
    }

    
    private void loadMahasiswaData() {
        List<Mahasiswa> mahasiswaList = controller.getAllMahasiswa();
        for (Mahasiswa mhs : mahasiswaList) {
            if (mhs.getNim().equals(mahasiswaId)) {
                DefaultTableModel model = (DefaultTableModel) mahasiswaTable.getModel();
                model.setRowCount(0); // clear existing rows

                model.addRow(new Object[]{"September", mhs.getKasSep() != null ? mhs.getKasSep().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Oktober", mhs.getKasOkt() != null ? mhs.getKasOkt().toString() : "Belum bayar"});
                model.addRow(new Object[]{"November", mhs.getKasNov() != null ? mhs.getKasNov().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Desember", mhs.getKasDes() != null ? mhs.getKasDes().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Februari", mhs.getKasFeb() != null ? mhs.getKasFeb().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Maret", mhs.getKasMar() != null ? mhs.getKasMar().toString() : "Belum bayar"});
                model.addRow(new Object[]{"April", mhs.getKasApr() != null ? mhs.getKasApr().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Mei", mhs.getKasMei() != null ? mhs.getKasMei().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Juni", mhs.getKasJun() != null ? mhs.getKasJun().toString() : "Belum bayar"});
                model.addRow(new Object[]{"Juli", mhs.getKasJul() != null ? mhs.getKasJul().toString() : "Belum bayar"});
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pembukuanButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        keluarButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pembukuanButton.setText("Pembukuan");
        pembukuanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembukuanButtonActionPerformed(evt);
            }
        });
        add(pembukuanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 95, -1));

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"September", null},
                {"Oktober", null},
                {"November", null},
                {"Desember", null},
                {"Februari", null},
                {"Maret", null},
                {"April", null},
                {"Mei", null},
                {"Juni", null},
                {"Juli", null}
            },
            new String [] {
                "Bulan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mahasiswaTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, 350));

        keluarButton.setText("Log Out");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });
        add(keluarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pembukuanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembukuanButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new MahasiswaPembukuan(contentScrollPane));
    }//GEN-LAST:event_pembukuanButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new Login(contentScrollPane));
    }//GEN-LAST:event_keluarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JButton pembukuanButton;
    // End of variables declaration//GEN-END:variables
}
