/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import controller.Controller;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class Pencatatan extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    private BendaharaPembukuan bendaharaPembukuan;
    private Controller controller;
    
    /**
     * Creates new form Pencatatan
     */
    public Pencatatan() {
        initComponents();
    }
    
    public Pencatatan(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        this.controller = new Controller();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jumlahTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transaksiComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tanggalDateChooser = new com.toedter.calendar.JDateChooser();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jumlahTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 360, -1));

        jLabel7.setText("Rp");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 20, -1));

        keteranganTextArea.setColumns(20);
        keteranganTextArea.setRows(5);
        jScrollPane1.setViewportView(keteranganTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, 130));

        jLabel1.setText("Jumlah");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });
        add(simpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        jLabel2.setText("Keterangan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel8.setText("Jenis Transaksi");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setText("Tanggal");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        transaksiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));
        add(transaksiComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 390, -1));

        jLabel4.setText(":");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 18, -1));

        jLabel9.setText(":");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 18, -1));

        jLabel5.setText(":");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel6.setText(":");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 18, -1));
        add(tanggalDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 390, -1));

        backButton.setText("Kembali");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new BendaharaView(contentScrollPane));
    }//GEN-LAST:event_backButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        String jenisTransaksi = (String) transaksiComboBox.getSelectedItem();
        double jumlah = Double.parseDouble(jumlahTextField.getText());
        String keterangan = keteranganTextArea.getText();
        java.util.Date utilDate = tanggalDateChooser.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(utilDate);

        String idUserBendahara = "000";
        boolean berhasilDisimpan = controller.simpanTransaksi(idUserBendahara, jenisTransaksi, tanggal, jumlah, keterangan);

        if (berhasilDisimpan) {
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
            contentScrollPane.setViewportView(new BendaharaView(contentScrollPane));
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi.");
        }
    }//GEN-LAST:event_simpanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahTextField;
    private javax.swing.JTextArea keteranganTextArea;
    private javax.swing.JButton simpanButton;
    private com.toedter.calendar.JDateChooser tanggalDateChooser;
    private javax.swing.JComboBox<String> transaksiComboBox;
    // End of variables declaration//GEN-END:variables
}
